version: '2'
services:
  phpfpm:
    image: rlewkowicz/php-fpm:7.0.13
    volumes:
    - "./distribution-files/etc:/usr/local/etc"
    - "./distribution-files/mwcore/mediawiki:/var/www/mediawiki"
    - "/etc/passwd:/etc/passwd:ro"
    - "/etc/shadow:/etc/shadow:ro"
    - "/etc/group:/etc/group:ro"
  nginx:
    image: nginx:1.10
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./distribution-files/nginx:/etc/nginx"
    - "./distribution-files/mwcore/mediawiki:/var/www/mediawiki"
    - "/etc/passwd:/etc/passwd:ro"
    - "/etc/shadow:/etc/shadow:ro"
    - "/etc/group:/etc/group:ro"
    depends_on:
    - phpfpm
  mysql:
    image: mariadb:10.0
    volumes:
    - "./distribution-files/mysql:/var/lib/mysql"
    environment:
    - MYSQL_ROOT_PASSWORD=@6gRzU2k8%
    - MYSQL_USER=root@myadmin
    - MYSQL_PASSWORD=@6gRzU2k8%
    depends_on:
    - nginx
