version: "3"

services:
  phpfpm:
    image: rlewkowicz/php-fpm:7.0.13
    volumes:
      - "/mnt/cephfs/dev/distribution-files/etc:/usr/local/etc"
      - "/mnt/cephfs/dev/distribution-files/mwcore/mediawiki:/var/www/mediawiki"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/shadow:/etc/shadow:ro"
      - "/etc/group:/etc/group:ro"
    deploy:
      placement:
        constraints: [node.role == worker]

  nginx:
    image: nginx:1.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/mnt/cephfs/dev/distribution-files/nginx:/etc/nginx"
      - "/mnt/cephfs/dev/distribution-files/mwcore/mediawiki:/var/www/mediawiki"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/shadow:/etc/shadow:ro"
      - "/etc/group:/etc/group:ro"
    depends_on:
      - phpfpm
      - parsoid
    deploy:
      placement:
        constraints: [node.role == manager]

  mysql:
    image: mariadb:10.0
    volumes:
      - "/mnt/cephfs/dev/distribution-files/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=@6gRzU2k8%
      - MYSQL_USER=root@myadmin
      - MYSQL_PASSWORD=@6gRzU2k8%
    depends_on:
      - nginx
    deploy:
      placement:
        constraints: [node.role == worker]
