version: "3"

traefik:
  image: traefik
  command: --docker --docker.swarmmode --docker.domain=traefik --docker.watch --web --configFile=/traefik.toml
  ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/mnt/cephfs/traefik/distribution-files/traefik/traefik.toml:/traefik.toml"
    - "/mnt/cephfs/traefik/distribution-files/nginx/ssl/wildcard.cert:/traefik.crt"
    - "/mnt/cephfs/traefik/distribution-files/nginx/ssl/wildcard.key:/traefik.key"
  networks:
    traefik
  deploy:
    placement:
      constraints: [node.role == manager]
